export const PALETTE = {
  POWDER_BLUE: "#90DAEE",

  CELADON_GREEN: "#ADE1C1",
  MEDIUM_GREEN: "#729780",
  DARK_GREEN: "#455E4F",

  MOUNTAIN_GRAY: "#6B705C",
  DESERT_YELLOW: "#E6C229",
  DEEP_WATER_BLUE: "#C1E4FF",
  SHALLOW_WATER_BLUE: "#D3ECFF",
  WALL_GRAY: "#A0A0A0",
  ROOF_GRAY: "#808080",
  LIGHT_GRAY: "#CCCCCC",
  JASMINE_YELLOW: "#FBD87F",
  BASE_WHITE: "#FFFFFF",
  WOOD_BROWN: "#8B4513",
} as const;

// Terrain Colors
export const TERRAIN_COLORS = {
  FOREST: PALETTE.CELADON_GREEN,
  PLAINS: PALETTE.CELADON_GREEN,
  MOUNTAINS: PALETTE.MOUNTAIN_GRAY,
  DESERT: PALETTE.DESERT_YELLOW,
  WATER: PALETTE.DEEP_WATER_BLUE,
} as const;

// Water Colors
export const WATER_COLORS = {
  DEEP: PALETTE.POWDER_BLUE,
  SHALLOW: PALETTE.POWDER_BLUE,
  BACKGROUND: PALETTE.POWDER_BLUE, // Sky/background color
} as const;

// Building Colors
export const BUILDING_COLORS = {
  WALL: PALETTE.DARK_GREEN,
  ROOF: PALETTE.DARK_GREEN,
  WINDOW_DAY: PALETTE.LIGHT_GRAY,
  WINDOW_NIGHT: PALETTE.JASMINE_YELLOW,
  BASE: PALETTE.BASE_WHITE,
} as const;

// Nature Colors
export const NATURE_COLORS = {
  TREE_TRUNK: PALETTE.WOOD_BROWN,
  TREE_LEAVES: PALETTE.MEDIUM_GREEN,
} as const;

// UI Colors
export const UI_COLORS = {
  PRIMARY: PALETTE.MEDIUM_GREEN,
  PRIMARY_DARK: PALETTE.DARK_GREEN,
  BACKGROUND: "rgba(0, 0, 0, 0.75)",
  TEXT_LIGHT: PALETTE.BASE_WHITE,
  TEXT_DARK: PALETTE.DARK_GREEN,
} as const;
